
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for k8s platform apps.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: datasources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for k8s datasources apps.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

---

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for k8s tenant apps.
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
