{{- $saas := index .Values "openframe-saas" -}}
{{- $svc := index $saas "gateway" -}}
{{- if and $saas.enabled $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: openframe-gateway
  labels:
    app: openframe-gateway
spec:
  selector:
    app: openframe-gateway
  ports:
    - port: 8100
      targetPort: 8100
      name: http
    - port: 8101
      targetPort: 8101
      name: management
  type: ClusterIP
{{- end }}
