{{- if .Values.meshcentral.enabled }}
{{- $creds := .Values.meshcentral.credentials | default dict }}
{{- $mongo := .Values.meshcentral.mongodb | default dict }}
apiVersion: v1
kind: Secret
metadata:
  name: meshcentral
type: Opaque
stringData:
  MESHCENTRAL_USER: {{ $creds.user | default "mesh@openframe.io" | quote }}
  MESHCENTRAL_PASSWORD: {{ $creds.password | default "meshpass@1234" | quote }}
  MESHCENTRAL_CONFIG_KEY: {{ $creds.configKey | default "openframe-mesh-config-key" | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: meshcentral-mongodb
type: Opaque
stringData:
  MC_MONGO_USER: {{ $mongo.user | default "meshcentral" | quote }}
  MC_MONGO_PASSWORD: {{ $mongo.password | default "meshcentral" | quote }}
{{- end }}
