apiVersion: v1
kind: ConfigMap
metadata:
  name: fleet-server
data:
  FLEET_SERVER_ADDRESS: "fleet-service.integrated-tools.svc.cluster.local"
  FLEET_SERVER_PORT: "8080"
  FLEET_SETUP_ADMIN_EMAIL: {{ .Values.fleet.environments.FLEET_SETUP_ADMIN_EMAIL | quote }}
